# Biblioteca

import pywhatkit
import keyboard
import time
import datetime
from datetime import datetime

# Contatos

contatos = ['+5511970714099']

# Mensagem

while len(contatos) >= 1:
    pywhatkit.sendwhatmsg(contatos[0], 'que perfume é esse que você passa e que fica com cheiro de amor da minha vida 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'o crime só compensa se for pra roubar uns beijos seus 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'onde é que eu deixo meu currículo para concorrer à vaga de amor da sua vida? 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'você não é asteroide, mas que corpo celeste você tem, hein 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'eu sei que as coisas não estão fáceis pra você, mas eu tô 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'você tem um mapa? me perdi no brilho dos seus olhos 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'super apoio esse casal: um tal de eu e você 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'você sabe estacionar? porque tem uma vaga pra você no meu coração 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'me chama de telefone que, com você, eu perco a linha 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'me chama de fritura, porque eu só tenho óleos pra você 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'eu não sou as Casas Bahia, mas prometo dedicação total a você 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'se meu coração fosse o Titanic, você certamente seria o Iceberg 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'oi, a minha cama tá querendo saber se você tá a fim de dormir com a gente 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'você não é Napoleão, mas ocupou uma bonaparte do meu coração 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'na minha terra tem palmeiras, onde canta o sabiá e eu quero saber que horas a gente vai se beijar 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'oi, você tem GPS? porque eu queria saber o caminho para a sua boca 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'desculpa ter te ligado pelo WhatsApp. eu só gostaria de abrir sua foto de perfil pra ver se era dólar ou euro, porque real não pode ser 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'você não é a Garota de Ipanema, mas é a coisa mais linda e cheia de graça que já vi. 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'você tem brigadeiro? não? então me dá um beijinho 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'está vendo aquela estrela ali no céu? mandei pendurar para você 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], '🤖 (pausa do bot) aproveite para ver esse vídeo recomendado pela autora: https://www.youtube.com/watch?v=tl9WC-OPP18', datetime.now().hour, datetime.now().minute + 2)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'vamos se beijar até o brasileiro criar consciência de classe 😍🤩 (nota da autora: grande crítica à nossa sociedade, achei interessante)', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'não sei fazer doces, mas dizem que o meu beijinho é o melhor. quer provar? 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'se você fosse um refrigerante, seria Soda, porque no meu coração soda você 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'ouvi dizer que você gosta de gatos. que tal me dar uma chance? 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'hoje é o seu aniversário, mas quero é dar parabéns aos seus pais por terem feito essa obra de arte! 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'fiquei surpresa quando você me disse "oi"... achava que gata só falava "miau". 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'sou péssima com idiomas mas quero conhecer uma língua nova, a sua 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'me chama de Natal que eu te mostro o que é noite feliz 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'não sou veterinária ou bióloga, mas sei reconhecer uma gatinha rara quando vejo 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'tá calor, né? mas não é de hoje que eu me derreto por você 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'aposto um beijo que você me dá um fora 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'não sou biscoito, mas eu adoraria ser seu passatempo 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'você acredita em amor à primeira vista ou devo passar por aqui mais uma vez? 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'para de curtir as minhas fotos e vem curtir a minha boca 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'existe um vazio no meu coração que tem as suas medidas. quer entrar? 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'estou fazendo uma campanha de doação de órgãos! não quer doar seu coração para mim? 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'estou sentindo solidão, mas poderia estar sentindo a sua boca na minha, né 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'igual a você, nem o Google encontra 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'não sou cimento, mas com você eu quero algo concreto 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'desculpe, eu não já fiquei com você antes? não?! então vamos dar um jeito nisso 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], '🤖 (pausa do bot) aproveite para ver esse vídeo recomendado pela autora: https://www.youtube.com/watch?v=JyWz-52kgEw', datetime.now().hour, datetime.now().minute + 2)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'a economia grega anda tão ruim assim? afinal, até uma deusa grega como você veio morar aqui 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'eu não sou manteiga de cacau, mas adoraria amaciar seus lábios 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'fui ler a previsão do tempo e vi que vai rolar um clima entre nós 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'como vou te dar meu mundo se meu mundo é você?? 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'quando a sua mãe dizia que queria o melhor para você, ela estava falando de mim, só para avisar 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'não precisa acender a luz pra ficar claro que eu quero você 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'mamãe fez um doce delícia pra você provar, o nome dele é EU 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'Seu nome é wi-fi? porque eu estou sentindo a conexão 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'nossa, tô sentindo uma dor no peito, espero que seja amor. porque, se for infarto, eu nunca mais vou ver você 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'me chama de terrorista que hoje eu tô atentada 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'você é o prego que faltava nas minhas havaianas 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'Você não é o ovo que faltava na minha marmita. você é o filé mignon! 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'é muito ruim conversar pelo WhatsApp. e se a gente morar junto pra facilitar? 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'eu não sou plano de saúde, mas, se você quiser, eu acabo com a sua carência 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'tem uma pessoa aí querendo muito dar uns beijos na sua boca, mas não vou falar que sou eu 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'eu estou te vendo online e olha que já passou da hora de bebê dormir hein 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'você não é marte, mas eu estou perdida em você 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], ' eu vim do futuro para te dizer que você perdeu a chance de me beijar uma vez, não perca de novo 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'não sou de esquerda nem direita, sou sua 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], 'vamos fazer uma operação lava-jato lá no meu chuveiro 😍🤩', datetime.now().hour, datetime.now().minute + 1)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], '🤖 (pausa do bot) aproveite para ver esse vídeo recomendado pela autora: https://www.youtube.com/watch?v=MrTz5xjmso4', datetime.now().hour, datetime.now().minute + 2)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], '🤖 (pausa do bot) e também tem esse rs: https://www.youtube.com/watch?v=LjhCEhWiKXk', datetime.now().hour, datetime.now().minute + 2)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
    pywhatkit.sendwhatmsg(contatos[0], '🤖 (pausa do bot): por hoje foi isso, feliz aniversário! 😀', datetime.now().hour, datetime.now().minute + 2)
    time.sleep(5)
    keyboard.press_and_release('ctrl + w')
